### PR TITLE
Fixed compilation errors so it works with V 0.4.3 

### PR DESCRIPTION
**Pull request by xn0px90**
added:
- @[attr] ---> from [attr]---> deprecated syntax 
- dependencies for sqlite.h ----> libsqlite3-dev

### CODE REVIEW

**Comment by scurty-labs** [comment]
Thank you for the fixes! Much appreciated.
